# This is a basic workflow to help you get started with Actions

name: CI-Cus-test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    # runs-on: ubuntu-latest
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          mkdir -p blackduck/output
          export JAVA_HOME=/usr/local/java/jdk-11.0.9/bin   
          /usr/local/java/jdk-11.0.9/bin/java -jar blackduck/synopsys-detect-9.10.0.jar \
          --blackduck.url="https://aws-eng-hub-sangjulee-test01.eng.aws.internal/" \
          --blackduck.api.token=NjJjZDcxNmEtNzRiYi00MDczLWFiNDktY2VmNzY5Y2UwOTQ2OmU4YjA1YTRiLTE5M2ItNDgwZC04YjUxLTNiOGRlNGViNzVjMw== \
          --blackduck.trust.cert=true \
          --detect.project.name=TMAP_ANDROID \
          --detect.project.version.name=1.0 \
          --detect.source.path=. \
          --detect.output.path=blackduck/output   \
          --detect.detector.search.depth=5 \
          --detect.accuracy.required=NONE \
          --detect.excluded.directories="**/build,./blackduck" \
          --detect.excluded.detector.types=NUGET \
          --logging.level.detect=DEBUG
